// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC11XpsB0slC8QoIhH_8arC5ZP910oUidM',
    appId: '1:800171431254:web:b9196dc8b44cea492db2f7',
    messagingSenderId: '800171431254',
    projectId: 'trampo-br-94c86',
    authDomain: 'trampo-br-94c86.firebaseapp.com',
    storageBucket: 'trampo-br-94c86.firebasestorage.app',
    measurementId: 'G-B39B784ZEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBIbzNGXIkGWl1R24B-_GglZlCcjbRNNc',
    appId: '1:800171431254:android:5ab029efc93ac3c12db2f7',
    messagingSenderId: '800171431254',
    projectId: 'trampo-br-94c86',
    storageBucket: 'trampo-br-94c86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAXqOqz5382BqWaDDQYh580Z2WDvgsUVw',
    appId: '1:800171431254:ios:dba04e1986c0e42d2db2f7',
    messagingSenderId: '800171431254',
    projectId: 'trampo-br-94c86',
    storageBucket: 'trampo-br-94c86.firebasestorage.app',
    iosBundleId: 'com.example.interpriseCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAXqOqz5382BqWaDDQYh580Z2WDvgsUVw',
    appId: '1:800171431254:ios:dba04e1986c0e42d2db2f7',
    messagingSenderId: '800171431254',
    projectId: 'trampo-br-94c86',
    storageBucket: 'trampo-br-94c86.firebasestorage.app',
    iosBundleId: 'com.example.interpriseCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC11XpsB0slC8QoIhH_8arC5ZP910oUidM',
    appId: '1:800171431254:web:39e10c2fb0897e1c2db2f7',
    messagingSenderId: '800171431254',
    projectId: 'trampo-br-94c86',
    authDomain: 'trampo-br-94c86.firebaseapp.com',
    storageBucket: 'trampo-br-94c86.firebasestorage.app',
    measurementId: 'G-ZQ16T9D5PN',
  );
}
